### ISSUE TITLE
Crash on play

### ISSUE THREAD

**Issue by Tenebruspt** [dresdner353/volumio2chromecast#1]
Hi there

Was looking for something to output from Volumio to chromecast audio and found your project which fit the bill for exactly of what I was looking for.

I followed the installation steps but am having problems getting it to run. I can find my Chromecast  Audio devices but it crashes when I start any playback. Here's the command I used:

volumio@volumio:~$ LC_ALL=en_US.UTF-8  ~/volumio2chromecast/volumio2chromecast.py --name 'Office speaker'

and the output I get:

`
Tue Nov 26 16:47:41 2019 No active Chromecast device

Tue Nov 26 16:47:42 2019 Volumio State:
{
    "updatedb": false,
    "repeatSingle": false,
    "disableVolumeControl": false,
    "uri": "music-library/NAS/Test/01 - Warm Sound.mp3",
    "album": "When It Falls",
    "channels": 2,
    "duration": 331,
    "title": "Warm Sound",
    "status": "play",
    "mute": false,
    "albumart": "/albumart?cacheid=948&web=Zero7/When%20It%20Falls/extralarge&pa                            th=%2Fmnt%2FNAS%2FTest&metadata=false",
    "volatile": false,
    "bitdepth": "24 bit",
    "artist": "Zero7",
    "stream": "mp3",
    "repeat": null,
    "trackType": "mp3",
    "samplerate": "44.1 kHz",
    "volume": 40,
    "position": 0,
    "random": null,
    "seek": 25135,
    "service": "mpd",
    "consume": false
}

Tue Nov 26 16:47:42 2019 Connecting to Chromecast 192.168.1.245:8009
Tue Nov 26 16:47:42 2019 Waiting for device to get ready..
Tue Nov 26 16:47:42 2019 Connected to Living Room speaker (192.168.1.245:8009) m                            odel:Unknown model name
Casting URL:b'http://192.168.137.54:8000/music/NAS/Test/01 - Warm Sound.mp3' typ                            e:audio/mp3
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/volumio/volumio2chromecast/volumio2chromecast.py", line 384, in vo                            lumio_agent
    autoplay = True)
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/controllers/media.py                            ", line 546, in play_media
    receiver_ctrl.launch_app(self.app_id, callback_function=app_launched_callbac                            k)
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/socket_client.py", l                            ine 1066, in launch_app
    lambda response: self._send_launch_message(
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/socket_client.py", l                            ine 1055, in update_status
    {MESSAGE_TYPE: TYPE_GET_STATUS}, callback_function=callback_function_param
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/controllers/__init__                            .py", line 90, in send_message
    self.send_message_nocheck(data, inc_session_id, callback_function)
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/controllers/__init__                            .py", line 94, in send_message_nocheck
    self._message_func(self.namespace, data, inc_session_id, callback_function)
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/socket_client.py", l                            ine 834, in send_platform_message
    callback_function_param,
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/socket_client.py", l                            ine 771, in send_message
    self._ensure_channel_connected(destination_id)
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/socket_client.py", l                            ine 883, in _ensure_channel_connected
    no_add_request_id=True,
  File "/usr/local/lib/python3.4/dist-packages/pychromecast/socket_client.py", l                            ine 822, in send_message
    "Chromecast {}:{} is connecting...".format(self.host, self.port)
pychromecast.error.NotConnected: Chromecast 192.168.1.245:8009 is connecting...

Detected 1 dead threads.. exiting
/usr/local/lib/python3.4/dist-packages/cherrypy/process/wspbus.py:258: RuntimeWa                            rning: The main thread is exiting, but the Bus is in the states.STARTED state; s                            hutting it down automatically now. You must either call bus.block() after start(                            ), or call bus.exit() before the main thread exits.
  'main thread exits.' % self.state, RuntimeWarning)
`
Any help you can provide is appreciated.

Thanks

**Comment by Tenebruspt** [comment]
So I did some more testing. Part of the problem is that the current version of pychromecast is no longer compatible with python 3.4.

I tried some earlier versions and version 2.3.0 of pychromecast runs. I can hear chromecast connect and i can change volume using the volumio UI, but no song actually plays (Elapsed stays at 0:00/0:00 [00%])

Interestingly, if I cast from phone while the script is running, the elapsed counter updates accordingly, and I can pause from the Volumio interface.

It looks like everything is working except for Chromecast to actually begin playing the proper song.

**Comment by joris-77** [comment]
Same issue here... And I only installed Volumio, because is seems chromecast playback was possible... I tried upgrading to a higher version of python but that seems to bring other problems.

**Comment by dresdner353** [comment]
Hi folks,
   sincere apologies.. I just saw this issue thread now, nearly a year later and I've been modifying the code all along. 

You are correct, the ancient Jesse image in Volumio is the cause of the issues here. 

I have it working again just recently but only on a the beta Buster images for Volumio. I tried all kinds of madness trying to recompile a later Python 3.x for the Jesse image and just kept running into issues. 

I also released a variant of the same script today for moOde another player similar in concept to Volumio.
